# This workflow will do a clean install of node dependencies,
# build the application and deploy it to production
# when a new version (git tag) is released

name: Build & Deploy

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 17
      uses: actions/setup-node@v1
      with:
        node-version: 17.x
    - name: Build app using Yarn
      run: |
        npm install -g yarn
        yarn install
        yarn build
    - name: Push Build files to production
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_PORT: ${{ secrets.DEPLOY_PORT }}
          REMOTE_USER: ${{ secrets.DEPLOY_USER }}
          TARGET: ${{ secrets.DEPLOY_PATH }}
